variable "public_subnet" {}
variable "private_subnet" {}
variable "vpc_cidr" {}
variable "key_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "db_allocated_storage" {}
variable "db_storage_type" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
