variable "ec2_count" {}
variable "ami_id" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "key_name" {}
variable "vpc_id" {}
variable "rds_endpoint" {}
variable "alb_sg" {}
variable "bastion_sg" {}
variable "name" {}
variable "username" {}
variable "password" {}
